[TIDL] Add reduce subgraph size pass
TexasInstruments/tvm pull request #7
Opened 2020-06-19 17:08 UTC by trevor-m

Thanks for contributing to TVM!   Please refer to guideline https://tvm.apache.org/docs/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/apache/incubator-tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.

2020-06-20 15:19 UTC, jianzhong-xu commented
@trevor-m , I tested resnet101_v1 with this PR, but still got this error "Error! Number of layers exceeds TIDL limit."
Can you test it on your branch? You'll just need to add 'resnet101_v1' to classification_models, and add the 2 new arguments to tidl.TIDLCompiler constructor:
        tidl_compiler = tidl.TIDLCompiler("AM57", (6,3), 
                                          num_tidl_subgraphs = num_tidl_subgraphs, 
                                          data_layout = data_layout, 
                                          artifacts_folder = artifacts_folder, 
                                          _max_num_layers = 256,
                                          max_total_memory_mb = 128                                          )_

2020-06-22 17:17 UTC, comaniac requested changes

2020-06-22 17:17 UTC, comaniac commented on python/tvm/relay/backend/contrib/tidl.py
> +        def Find(self, expr):
`Find` doesn't match the naming convention in Python. Maybe you can consider embedding this function to the constructor.

2020-06-22 17:17 UTC, comaniac commented on python/tvm/relay/backend/contrib/tidl.py
> +def FindCommonAncestor(expr0, expr1):
Overall I think this function could be simplified. Currently, it passes the graph twice and maintains two paths of each given expression, but we should be able to achieve this goal with only one pass so that the time and space complexity could be reduced.

2020-06-22 17:17 UTC, comaniac commented on python/tvm/relay/backend/contrib/tidl.py
> +        new_mod['main'] = reducer.visit(mod["main"])
This might be a problem if your module includes `Preclude` (i.e., the given module multiple functions other than `main`). If this implementation works for all test cases you have in hand, at least you could add a TODO for now.

2020-06-22 17:17 UTC, comaniac commented on python/tvm/relay/backend/contrib/tidl.py
> +    while sanity_counter > 0:
What would be the usual number of ops reduced here? Would those reduced op be the performance bottleneck if we simply fallback all of them to CPU?

2020-06-22 18:41 UTC, trevor-m commented
> @trevor-m , I tested resnet101_v1 with this PR, but still got this error "Error! Number of layers exceeds TIDL limit."
> Can you test it on your branch? You'll just need to add 'resnet101_v1' to classification_models, and add the 2 new arguments to tidl.TIDLCompiler constructor:
> tidl_compiler = tidl.TIDLCompiler("AM57", (6,3),
> num_tidl_subgraphs = num_tidl_subgraphs,
> data_layout = data_layout,
> artifacts_folder = artifacts_folder,
> _max_num_layers = 256, max_total_memory_mb = 128 )_

Hey Jiaznhong, thanks for testing. I found that after rebasing which brought in some annotation changes, the number of layers being detected was only 248. The way we calculate number of layers does not perfectly match TIDL. To be safe, I lowered max_num_layers to 200. After doing that I found a new situation that the ReduceSubgraphSize pass isn't able to handle. I'm currently fixing it and adding a new test case.

2020-06-23 22:01 UTC, trevor-m commented on python/tvm/relay/backend/contrib/tidl.py
> +    while sanity_counter > 0:
For example for Resnet 152, it starts with 616 layers and we remove 391 and put those all on the CPU.

2020-06-24 16:34 UTC, trevor-m commented
@jianzhong-xu Could you try again? It should be working now.

2020-06-24 17:37 UTC, jianzhong-xu commented on python/tvm/relay/backend/contrib/tidl.py
> +        mod = ReduceSubgraphSize(mod, max_num_layers=max_num_layers, max_total_memory_mb=max_total_memory_mb, compiler=self.tidl_target)
self.max_num_layers and self.max_total_memory_mb should be used here.

2020-06-24 17:38 UTC, jianzhong-xu commented
@trevor-m I tested and it worked fine. Can you fix the typo mentioned in the other comment? Then I'll merge it.

2020-06-24 20:07 UTC, merged